/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LegislativeWinsRouteImport } from './routes/legislative-wins'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GetHelpRouteImport } from './routes/get-help'
import { Route as CedLawRouteImport } from './routes/ced-law'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTeamRouteImport } from './routes/admin.team'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislativeWinsRoute = LegislativeWinsRouteImport.update({
  id: '/legislative-wins',
  path: '/legislative-wins',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetHelpRoute = GetHelpRouteImport.update({
  id: '/get-help',
  path: '/get-help',
  getParentRoute: () => rootRouteImport,
} as any)
const CedLawRoute = CedLawRouteImport.update({
  id: '/ced-law',
  path: '/ced-law',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/ced-law': typeof CedLawRoute
  '/get-help': typeof GetHelpRoute
  '/impact': typeof ImpactRoute
  '/legislative-wins': typeof LegislativeWinsRoute
  '/news': typeof NewsRoute
  '/our-work': typeof OurWorkRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/ced-law': typeof CedLawRoute
  '/get-help': typeof GetHelpRoute
  '/impact': typeof ImpactRoute
  '/legislative-wins': typeof LegislativeWinsRoute
  '/news': typeof NewsRoute
  '/our-work': typeof OurWorkRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/ced-law': typeof CedLawRoute
  '/get-help': typeof GetHelpRoute
  '/impact': typeof ImpactRoute
  '/legislative-wins': typeof LegislativeWinsRoute
  '/news': typeof NewsRoute
  '/our-work': typeof OurWorkRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/ced-law'
    | '/get-help'
    | '/impact'
    | '/legislative-wins'
    | '/news'
    | '/our-work'
    | '/research'
    | '/team'
    | '/admin/team'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/ced-law'
    | '/get-help'
    | '/impact'
    | '/legislative-wins'
    | '/news'
    | '/our-work'
    | '/research'
    | '/team'
    | '/admin/team'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/ced-law'
    | '/get-help'
    | '/impact'
    | '/legislative-wins'
    | '/news'
    | '/our-work'
    | '/research'
    | '/team'
    | '/admin/team'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  CedLawRoute: typeof CedLawRoute
  GetHelpRoute: typeof GetHelpRoute
  ImpactRoute: typeof ImpactRoute
  LegislativeWinsRoute: typeof LegislativeWinsRoute
  NewsRoute: typeof NewsRoute
  OurWorkRoute: typeof OurWorkRoute
  ResearchRoute: typeof ResearchRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislative-wins': {
      id: '/legislative-wins'
      path: '/legislative-wins'
      fullPath: '/legislative-wins'
      preLoaderRoute: typeof LegislativeWinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-help': {
      id: '/get-help'
      path: '/get-help'
      fullPath: '/get-help'
      preLoaderRoute: typeof GetHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ced-law': {
      id: '/ced-law'
      path: '/ced-law'
      fullPath: '/ced-law'
      preLoaderRoute: typeof CedLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  CedLawRoute: CedLawRoute,
  GetHelpRoute: GetHelpRoute,
  ImpactRoute: ImpactRoute,
  LegislativeWinsRoute: LegislativeWinsRoute,
  NewsRoute: NewsRoute,
  OurWorkRoute: OurWorkRoute,
  ResearchRoute: ResearchRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
